import { useEffect, useState } from "react";
import { getServices } from "../helpers/getServices";

export const useFetchServices = (): FetchServicesResult => {
  const [isLoading, setIsLoading] = useState(true);
  const [services, setServices] = useState<Service[]>([]);
  const [error, setError] = useState<string | undefined>();

  const getServicesData = async () => {
    try {
      const data = await getServices();
      setServices(data.services);
    } catch (error) {
      console.error('Error al obtener los servicios', error);
      setError('Error al obtener los servicios');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    getServicesData();
  }, []);

  return {
    services,
    isLoading,
    error
  };
};

// Generated by https://quicktype.io

export interface FetchServicesResult {
  services: Service[];
  isLoading: boolean;
  error?: string;
}

export interface Service {
  id:                  number;
  name:                string;
  description:         string;
  price:               number;
  cost:                number;
  duration:            number;
  service_category_id: number;
  created_at:          string;
  updated_at:          string;
  category_name:       string;
  category:            Category;
}

export interface Category {
  id:              number;
  name:            string;
  parent_category: null;
  created_at:      string;
  updated_at:      string;
}
